### PR TITLE
Improve Windows ldflags linking

### PR DESCRIPTION
**Pull request by cdeterman**
My commits are related to the `ldflags` function.  It takes inspiration from some Rcpp package to improve how the ldflags are generated for Windows which often has problems with spaces and the backslashes.

### CODE REVIEW

**Comment by wrathematics** [comment]
Thanks for taking a look at this. Lately my work/life balance has been all work (no life or balance), so I haven't had a chance to test it yet, but I plan to tomorrow.

**Comment by wrathematics** [comment]
This still doesn't work in my windows vm, although I'm not sure if now it's a real problem or just one that lives in my vm.

@snoweye any chance I could get you to take a look at this? You can test if it works by trying to install `rbigdata/kazaam`. I understand if you're busy and don't have time.

**Comment by snoweye** [comment]
I don't see this PR has any trouble to me as long as `ldflags_string()` is not called in which I won't because I don't know how/where it works for...

You do have a problem in `kazaam` in windows, so that I send a PR which passed my native windows for both `float` and `kazaam`. Please check.
I don't see how/where `ldflags_string()` is called in `kazaam` ...

**Comment by wrathematics** [comment]
Huh, weird. That's not the error I see.

The function is called in Makevars:
* https://github.com/RBigData/kazaam/blob/master/src/Makevars.in#L4
* https://github.com/RBigData/kazaam/blob/master/src/Makevars.win#L12

**Comment by snoweye** [comment]
Oh, sorry, I did not actually get the PR to my local. What I tested was the original version. No, this PR should be closed and not to be merged for 2 reasons:
- For long term, win32 should be gone and 8+3 should be avoided.
- The original version is safe enough even with spaces or backslashes which had been taken care.

`kazaam` has its own problem not related to this one.

One more thing, this approach, `ldflags()`, will very likely fail when an end user install this from CRAN's mac binary...

**Comment by cdeterman** [comment]
@snoweye wwhat logic would be better for Mac?  I'm also not sure why you are referencing win32 as nothing is explict in the code change regarding it.  I just know that spaces often come up in Windows paths and this helps make sure it isn't an issue regardless if win32 is there or not.  Also, I have no clue what you are referring to with 8+3.

Ultimately this isn't that big of a change so if it wants to be declined that is fine.  It was just my thought to make sure Windows builds are a little smoother.

**Comment by snoweye** [comment]
`?shortPathName" has a section of details why/what 8+3 is. That is for old DOS naming rules.

`?file_path_as_absolute` has a section of details that was called outside before your changes.
You still need to append `flags<-paste0(flags, "/float.*")` to your changes to make this PR working.

I guess your changes may be already covered by the `file_path_as_absolute()`.

The easy way to make mac works is to build a static `float.a` in addition to `float.*.dylib`, then the `LinkingTo` idea can follow.

Otherwise, you need a very complicate way for downstream packages that needs `float` package. The solution is in `pbdZMQ` which export a shared library only but linked by `JuniperKernel`.

**Comment by wrathematics** [comment]
I've been trying to avoid a static library because I don't really want every package that links to float to get a large install size NOTE. But I guess until they actually make the LinkingTo field do what it says, that's the only option. Maybe I'll just do it for Windows and Mac.

Thanks, everyone.

**Pull request closed without merging**
